mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: :9090
dns:
  enable: true
  enhanced-mode: fake-ip
  ipv6: false
  listen: 0.0.0.0:53
  nameserver:
    - https://dns.zhebk.cn/dns-query
  fallback:
    - https://dns.zhebk.cn/dns-query
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
