port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
ipv6: true
external-controller: :9090
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - 112.124.101.139
  nameserver:
    - https://dns.zhebk.cn/dns-query
