port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
ipv6: true
external-controller: :9090
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 1.1.1.1
  nameserver:
    - https://dns.zhebk.cn/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - tcp://208.67.222.222:443
    - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
